---
output: 
  html_document:
    includes:
      in_header: iframe_resizer.html
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(kableExtra)
knitr::opts_chunk$set(echo = FALSE)
```

## Chapter 4 Exercise

Recreate the following dataframe, and store it under the name `tiktokers`.

```{r, echo=FALSE, results='hide'}
tiktokers<- data.frame(
  user= c("khaby.lame", "charlidamelio", "bellapoarch", "addisonre", "willsmith", "zachking", "kimberly.loaiza", "tiktok", "cznburak", "dixiedamelio"),
  rank= c(1:10),
  brand= c(rep(FALSE, 7), TRUE, rep(FALSE, 2)),
  followers_mill= c(142.9, 142.3, 90.1, 87.9, 72, 68.7, 63.6, 62.9, 59, 57.4),
  likes_mill= c(2286.9, 10960.3, 2096.8, 5682.3, 437.3, 866.9, 3723.9, 268.8, 1057.7, 3202.8)
)
```

```{r, echo=FALSE, fig.cap="Table for Chapter 4 Exercise"}
knitr::kable(tiktokers, caption="Table for Chapter 4 Exercise", booktabs=FALSE) %>%
  kable_styling(position= "center")
```

```{r create-dataframe, exercise=TRUE}
# Recreate the following Dataframe here:


```

```{r create-dataframe-hint}
best_cats <- data.frame(
  variable_1= c(),
  variable_2= c(),
  variable_3= c()
)
```

```{r create-dataaframe-solution}
tiktokers<- data.frame(
  user= c("khaby.lame", "charlidamelio", "bellapoarch", "addisonre", "willsmith", "zachking", "kimberly.loaiza", "tiktok", "cznburak", "dixiedamelio"),
  rank= c(1:10),
  brand= c(rep(FALSE, 7), TRUE, rep(FALSE, 2)),
  followers_mill= c(142.9, 142.3, 90.1, 87.9, 72, 68.7, 63.6, 62.9, 59, 57.4),
  likes_mill= c(2286.9, 10960.3, 2096.8, 5682.3, 437.3, 866.9, 3723.9, 268.8, 1057.7, 3202.8)
)
```
<div data-iframe-height></div>